### ISSUE TITLE
bug(test_runner): 'required field "Type" not set'

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1379]
Seeing this error in many places in the `cmd` package.

Will walk through one example to try to illustrate. Let's take `TestUnlinkBasic`

- we create a test runner. dope.
- we run a bunch of command line commands with no errors! yay! ty channels
- we call `run.LookupVersionInfo()`, which runs `run.RepoRoot.Repo()` which errors with `required field "Type" not set`

on further examination, if you follow the code down
`run.RepoRoot.Repo()` -> `NewMemRepoFromDir` -> `ReadRepoConfig`
printing out the config this is what it contains:

```
API:
  allowedorigins:
  - electron://local.qri.io
  - http://localhost:2505
  - http://app.qri.io
  - https://app.qri.io
  enabled: true
  port: 2503
  proxyforcehttps: false
  readonly: false
  remoteacceptsizemax: 0
  remoteaccepttimeoutms: 0
  remotemode: false
  serveremotetraffic: false
  tls: false
  urlroot: ""
CLI:
  colorizeoutput: false
Logging:
  levels:
    qriapi: info
    qrip2p: info
P2P:
  addrs: null
  autoNAT: false
  bootstrapaddrs: null
  enabled: true
  httpgatewayaddr: https://ipfs.io
  peerid: QmeL2mdVka1eahKENjehK6tBxkkpk5dNQ1qMcgWi7Hrb4B
  port: 0
  privkey: CAASqAkwggSkAgEAAoIBAQChp1HiZxTsLQCaHmW3/cc2ZDZpgLwn5o1/nZPgqT7SyXHP5bn7GQMG3kPEQWcl4nhtLX9hkrBEskHrdIlqp9zXFMwBfat+qfzCylGC/QBDF7wT9umLd7nbq7pAxQXteXgntt2Zhg4gE/kEk7vIyL+P9KpWJZ/yjpykgsDC7NPnrr8qZBo2tL0F4w+33nZhEx7Pp7Rnaq22JM8rF+NHCgSkUh63lp7Vhwm9PQoGtt0XTnEKxrMQnUme/IhGNxs84RphxHc5+nW6jYjgm5bcJonGyPU7bq+v51Mr2Ol4RT3L9ZNJgz0SWTSmAtiBLx2ryLrTjmDPSvN7wLm9sWEdWmRVAgMBAAECggEBAJMumrl+jWgz2TZ5sreBEp6NQ5VvpuDVY8PrnzaQIikdTMizK1BaB417VUwdGGM//dG5+R7HxkHl42sT4gH/8GzL/Krm1vwunXplZy3SWSi9NXsf9qgLTGebxasvOCRt0l6mesFLcxT12ma2c+VuEixp4aUqAKWB/1Ex03wm0RFBcSttPHe5ODW8Eaz+ZU8cpObEcZdCIPVxeWqLVdkAImOmsknL0EAxP8Wo/V6Rh5Cg4PnwnfJiQ45C+m6h7NTIw0H4UOncv7EBABra6LqF6Uoda9vmv8CpwaXwR557DPchQglFjtm48jWGeVKO3Zyutizu420eRrFZ0GmJo5flvkkCgYEA0SLysOZNxDgjYA0ihVYL6UbCvYUSADuDyTWREOUiRfmxAmS1xN9o7fieCJnA4aAAnSugtT2BI7HEqT1lLz0YF8NRDKL07TNbkmNLIHXBbXA5saf10N2juhflfIm5/b/W9lC3QsngMR27J25Ztqof6Ur36bIKJ6Y6XvYdlkkZkc8CgYEAxeCHUWMvtHtBID9ZOtrZRNhNJ/uz+2rzVSPd6ZdhEUWsvv/0p7JXmSAp2eoJDDKHeSnVxcxQMqhq0/edUSSzSvDpWha8UU4N8hRpu+M0XZNke0ijhpK6NIqNHPvZdsyFD0VR1Vaj2Ruy+pzih6PhqSnn2ZwvpQJAwBnqc2VCJJsCgYAkQr33hAbpxZ4EkmJw4elwye8L8x2a4rbH1TzQxBm8Lj3Nn26Qsve7gwbLkPULabWRirXzlrVkXfcuLNH1bc9Wl2vfGAYFdokjCYpGF4SxF+s47VlGnJc9tdT5UdvorjF0RaxwrRXtDi2b+Zsee8LKrU/sugzesQif3GZm30fKqwKBgQCQHwHP+HMFfAQqLZma8UzwBK7loUEsrHAAoff+K8CKKPoxvxD9lzqQD8oLqpbeaGsdh6fowe/jhaERM7dEI3vm6GK9t/N/MF+d4tpD+67nPPQhiv13haTTodo3swNnsHx1a+K3hLwf5DnOqLehXW59nET+zPAyudpZUEbft2+eYwKBgCMS6SitXwa2UjFNgkMAaOeJjkjnUKcr1tO/zPtaYPugKgkMQB890q4dcq5rnG2onhJ7hkoMwcrFugbD2nub9AIkaMc6Y46jyh2mSeA0337MpoMp99Jmp2/B1rouYo4IRS25b7jk22yjV8ARCzsxFVQxEwA1Lg8YpaXaifuI+/2O
  profilereplication: full
  pubkey: ""
  qribootstrapaddrs:
  - /ip4/35.239.80.82/tcp/4001/ipfs/QmdpGkbqDYRPCcwLYnEm8oYGz2G9aUZn9WwPjqvqw3XUAc
  - /ip4/35.225.152.38/tcp/4001/ipfs/QmTRqTLbKndFC2rp6VzpyApxHCLrFV35setF1DQZaRWPVf
  - /ip4/35.202.155.225/tcp/4001/ipfs/QmegNYmwHUQFc3v3eemsYUVf3WiSg4RcMrh3hovA5LncJ2
  - /ip4/35.238.10.180/tcp/4001/ipfs/QmessbA6uGLJ7HTwbUJ2niE49WbdPfzi27tdYXdAaGRB4G
  - /ip4/35.238.105.35/tcp/4001/ipfs/Qmc353gHY5Wx5iHKHPYj3QDqHP4hVA1MpoSsT6hwSyVx3r
  - /ip4/35.239.138.186/tcp/4001/ipfs/QmT9YHJF2YkysLqWhhiVTL5526VFtavic3bVueF9rCsjVi
  - /ip4/35.226.44.58/tcp/4001/ipfs/QmQS2ryqZrjJtPKDy9VTkdPwdUSpTi1TdpGUaqAVwfxcNh
Profile:
  color: ""
  created: "2020-06-01T22:27:26.042681-04:00"
  description: ""
  email: ""
  homeurl: ""
  id: QmeL2mdVka1eahKENjehK6tBxkkpk5dNQ1qMcgWi7Hrb4B
  name: ""
  peername: test_peer
  photo: ""
  poster: ""
  privkey: CAASqAkwggSkAgEAAoIBAQChp1HiZxTsLQCaHmW3/cc2ZDZpgLwn5o1/nZPgqT7SyXHP5bn7GQMG3kPEQWcl4nhtLX9hkrBEskHrdIlqp9zXFMwBfat+qfzCylGC/QBDF7wT9umLd7nbq7pAxQXteXgntt2Zhg4gE/kEk7vIyL+P9KpWJZ/yjpykgsDC7NPnrr8qZBo2tL0F4w+33nZhEx7Pp7Rnaq22JM8rF+NHCgSkUh63lp7Vhwm9PQoGtt0XTnEKxrMQnUme/IhGNxs84RphxHc5+nW6jYjgm5bcJonGyPU7bq+v51Mr2Ol4RT3L9ZNJgz0SWTSmAtiBLx2ryLrTjmDPSvN7wLm9sWEdWmRVAgMBAAECggEBAJMumrl+jWgz2TZ5sreBEp6NQ5VvpuDVY8PrnzaQIikdTMizK1BaB417VUwdGGM//dG5+R7HxkHl42sT4gH/8GzL/Krm1vwunXplZy3SWSi9NXsf9qgLTGebxasvOCRt0l6mesFLcxT12ma2c+VuEixp4aUqAKWB/1Ex03wm0RFBcSttPHe5ODW8Eaz+ZU8cpObEcZdCIPVxeWqLVdkAImOmsknL0EAxP8Wo/V6Rh5Cg4PnwnfJiQ45C+m6h7NTIw0H4UOncv7EBABra6LqF6Uoda9vmv8CpwaXwR557DPchQglFjtm48jWGeVKO3Zyutizu420eRrFZ0GmJo5flvkkCgYEA0SLysOZNxDgjYA0ihVYL6UbCvYUSADuDyTWREOUiRfmxAmS1xN9o7fieCJnA4aAAnSugtT2BI7HEqT1lLz0YF8NRDKL07TNbkmNLIHXBbXA5saf10N2juhflfIm5/b/W9lC3QsngMR27J25Ztqof6Ur36bIKJ6Y6XvYdlkkZkc8CgYEAxeCHUWMvtHtBID9ZOtrZRNhNJ/uz+2rzVSPd6ZdhEUWsvv/0p7JXmSAp2eoJDDKHeSnVxcxQMqhq0/edUSSzSvDpWha8UU4N8hRpu+M0XZNke0ijhpK6NIqNHPvZdsyFD0VR1Vaj2Ruy+pzih6PhqSnn2ZwvpQJAwBnqc2VCJJsCgYAkQr33hAbpxZ4EkmJw4elwye8L8x2a4rbH1TzQxBm8Lj3Nn26Qsve7gwbLkPULabWRirXzlrVkXfcuLNH1bc9Wl2vfGAYFdokjCYpGF4SxF+s47VlGnJc9tdT5UdvorjF0RaxwrRXtDi2b+Zsee8LKrU/sugzesQif3GZm30fKqwKBgQCQHwHP+HMFfAQqLZma8UzwBK7loUEsrHAAoff+K8CKKPoxvxD9lzqQD8oLqpbeaGsdh6fowe/jhaERM7dEI3vm6GK9t/N/MF+d4tpD+67nPPQhiv13haTTodo3swNnsHx1a+K3hLwf5DnOqLehXW59nET+zPAyudpZUEbft2+eYwKBgCMS6SitXwa2UjFNgkMAaOeJjkjnUKcr1tO/zPtaYPugKgkMQB890q4dcq5rnG2onhJ7hkoMwcrFugbD2nub9AIkaMc6Y46jyh2mSeA0337MpoMp99Jmp2/B1rouYo4IRS25b7jk22yjV8ARCzsxFVQxEwA1Lg8YpaXaifuI+/2O
  thumb: ""
  twitter: ""
  type: peer
  updated: "2020-06-01T22:27:26.042681-04:00"
RPC:
  enabled: true
  port: 2504
Registry:
  location: https://registry.qri.cloud
Remote: null
Remotes: null
Render:
  defaultTemplateHash: /ipfs/QmeqeRTf2Cvkqdx4xUdWi1nJB2TgCyxmemsL3H4f1eTBaw
  templateUpdateAddress: /ipns/defaulttmpl.qri.io
Repo:
  middleware: []
  type: fs
Revision: 1
Stats:
  cache:
    maxsize: 25600
    type: fs
Store:
  options:
    api: true
  path: /var/folders/4d/4pgbh8d1083g1f7skny7bwy00000gn/T/qri_test_fsi_unlink795291625/ipfs
  type: ipfs
Update:
  address: 127.0.0.1:2507
  daemonize: true
  type: fs
Webapp:
  analyticstoken: ""
  enabled: true
  entrypointhash: QmfWr3jS97PNNUH5bg39nig4Jd8JDnXvRxvytmFpWnTPLn
  entrypointupdateaddress: /ipns/webapp.qri.io
  port: 2505
```

But it looks like the `ReadRepoConfig` function expects a different structure (taken from `TestNewMemRepoFromDir`):
```
peerid: QmSgrhorPVg2nf4ghr4EnGbnVCjtWumZrgdxtpm1EBvw3d
privatekey: CAASpwkwggSjAgEAAoIBAQCoqoxGxSpIM2vZ0g4sGJkn43wuKIZufpjubLlUYXo2zkOcc32HknyWKuChtlL1cQHJSLSq2S1D2q3Hz98toSGBemh+R5F1JJJJjxNWdAVo+MmJFcSfkqxyanIc/TxYQLPjZSEcw0ahac5rxsiSoXmH9o5BOsjyEbNTEyBzG37sEMbWO1YNa2cBG203YXKxT/+nSHnZ6LlcaOuCndhbiXDYOZn/nJtBAmx/7l0TwOOxfIxOMMEMUeAVR2n9BVnhyHHi4A7wEF4yBGAGZZxitLRrVFCX61QBwauOoddaqH+veYzAWi2tRLFMFKDogJtcaMApcMPMTXPjhzrfbrYoWsVLAgMBAAECggEAeyo3T0KRErJCEoiagsbfqEotF0POjwdxQ8IvP5gC99x9cNTBGOv2gG4FJPGP+N0x0bt++remn0Mj3aJFNfvRDMzHW1eFt4YiMQcCtwH4JWRvPuSfdWtU9CQY+mRN2aA9/FKP8IIEpMAv1XIOa0zxA0EfNjDoJiSYz5RLAONWNqkF0oO68yi96rEd7jQOWdugi2rXqsvyJRdyurCu1h+OupQaylt6vkzaiChFbNBQt5ecHgWb418T16jBe1ePs0oGuQuQz/0Pj4TcDa2ENW6pKWglQ5/poh2lEfPHKAauiHozwdzBB/8YSNwjcQ+GzC9zkTDaXY0f0BwDSr8+pdmTgQKBgQDGxksqoNbiuOGDwnzAxQMuJKBwBszMkg27A6XOzhIK3ZvRbCkSiq7NMBAkKgdH91rUcImn2QZ1u4phaFMqBAoKKWSHegqOMEw5nDln6B/IB20qwwgNPCm2lQoUvLyPyFwhlo5bqFUQfrgRRYmLWKMA0EKZwpNQkhToX1iYAgmfCwKBgQDZOUN/gSpwt7BTTQfY8kk4tq5rayzCadCUgrH0JrXNwQsE2rv2bUo1X/9Ft/vKv2YkbQZ7U9WaGtllBAT7lU4wKUqbARlbFwivg3452CxaSma8JxQQ1cNP0CXBiZGKy57/gOakZuxdE0jy9JWcPfXhqnRzXRZmdKEwv2s7tZBawQKBgQDA1Tmyfxo4FJdiVVjlQbsWFp42T8J6au47EQzXlX5XYCl7fuxReoydrhTaoJMzs7lAAnToilgD+w4B9U1Io2aB+Sn3a+O1kRFBilb+gGfki5/SLiYvgMAOyoNfHsHm0r7eLsqoDKOJPwWea9FFh5WKgn8531M+hJkX3Pd7b+6ZhQKBgB92H8ST3KW+tRcbjQtq7Bf+vXxpZW4zDTa1RzjpcmN+li350Ed8xMa+RKbAYwOWfSDBebLbDZDoWpw63M3jbhOjp16T5iw/Rc7F6L5QBPx+0ipmLo3RqBwjNZS2bBICM+EltkIRdiJ07JfjvNeIUdiBa6RZ0yi7s6zvzIQ1Y9cBAoGAXAM4x4Mx9Cztqy6ZJOiJImKmRR/rFGC3pKtBRfbR7nVSjFhltSa7m7lKaai130UQhlA/OK6ehyJTmmT69p2ge7CTM/fHHsv6POw+xr6F0ewMtA2SN3N/wNwY3tlYJYZPZRy/hXGRTjC2POSJTCY3wtudZmu3XpcdNDeQHtbAtm8=
profile:
  id: QmSgrhorPVg2nf4ghr4EnGbnVCjtWumZrgdxtpm1EBvw3d
  created: "0001-01-01T00:00:00Z"
  updated: "0001-01-01T00:00:00Z"
  peername: "sea_blue_border_collie"
```

Tests inside the **cmd** packages that rely on test runner have a config that looks like the former.
Tests inside the **p2p** package that rely on `NewTestDirNetwork` expect the config to look like the latter.

But both rely on the test runner func `NewMemRepoFromDir`.

This is its own issue and I'm not sure what exactly is going on there.

I've already written a `NewIPFSRepoFromDir` (which needs a re-name) that expects a normal qri config & returns a repo... but when I use that function to create a repo instead of `NewMemRepoFromDir`, `TestUnlinkBasic` runs without panicking (yay) but now the thing we are testing fails (boo). (I've pushed my latest version that shows this)

Now, however, `TestUnlinkBasic` fails with `not found: me/unlink_me`! lines 1533-1537:
```
	// Verify that reference in refstore does not have FSIPath
	vinfo := run.LookupVersionInfo(t, "me/unlink_me")
	if vinfo == nil {
		t.Fatal("not found: me/unlink_me")
	}
```
So we don't actually get a VersionInfo when we try to look it up in `LookupVersionInfo`... and I can't figure out why. Maybe something to do with the fact that this particular test uses a `NewFSITestRunner` and not a usual `TestRunner`? Is it something to do with `dscache`?

I can't really see the forest for the trees right now and would like another set of eyes if possible!
