### ISSUE TITLE
unicode byte-order-mark is not handled gracefully

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1425]
Downloaded the csv from https://www.cdc.gov/nchs/pressroom/sosmap/heart_disease_mortality/heart_disease.htm

The csv begins with the following bytes: `\xef\xbb\xbf\x22\x59\x45\x41\x52\x22`. That's the [byte order mark](https://unicode.org/faq/utf_bom.html) followed by "YEAR". Our detect code does not properly pass over the byte order mark, so the structure has a schema with strange column names:

```
  schema:
    items:
      items:
      - title: "\uFEFF\x5F\x79\x65\x61\x72"
        type: integer
      - title: state
        type: string
      - title: rate
        type: number
      - title: deaths
        type: string
      - title: url
        type: string
      type: array
    type: array
```

This is another argument in favor of doing https://github.com/qri-io/qri/issues/1371 in order to make it easier to fix bugs in `dataset/detect`.
