### ISSUE TITLE
Modifying config for automation controls

### ISSUE THREAD

**Issue by b5** [qri-io/qri#1748]
We need to expand configuration to control the automation subsystem. I'd err on the side of keeping this as small as possible for now:

```yaml
automation:
  enabled: true                # controls if the local scheduler should run
  runLogMaxCacheSize: 100Mb    # what's the max space run log files can consume?
```

### `automation.enabled`
flipping `automation.enabled` to `false` should prevent the local node from running a workflow without the user explicitly telling qri to do so (via `qri apply`). In practice this prevents the `scheduler` subsystem from being assigned when the instance is constructed.

### `automation.runLogMaxCacheSize`
once we have the `runStore` up, executing a run will create a log file of newline-delimited JSON events that describe the execution of a script in detail. Each run should be persisted as a "run log", up until the total size of those run logs exceeds the value of `runLogMaxCacheSize`, at which point `runStore` will delete the oldest log files until the total size of the store is less than `runLogMaxCacheSize`. Setting `runLogMaxCacheSize` to `-1` allows an unlimited cache size. Setting `runLogMaxCacheSize` to `0` disables log retention entirely.
