### ISSUE TITLE
docs(config): need to update documentation to the `qri config`

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#334]
add documentation to explain you can get an set different aspects of the config by using the `qri config get` and `qri config set` commands 

`qri config get profile.peername`
`qri config set profile.peername newPeername`

Need documentation to show different paths and fields you can change. Not sure the best place or way to show this. Should it be in the qri config --help command?

and do I just list it like this?

```
profile:
  id: 
  privkey: 
  peername:
  created:
  updated:
  type:
  email:
  name:
  description:
  homeurl:
  color:
  thumb:
  profile:
  poster:
  twitter:
repo:
  middleware: []
  type:
store:
  type:
p2p:
  enabled:
  peerid: 
  pubkey: 
  privkey: 
  port:
  addrs: []
  qribootstrapaddrs: []
  profilereplication:
  boostrapaddrs: []
cli:
  colorizeoutput: 
api:
  enabled:
  port:
  readonly:
  urlroot:
  tls:
  proxyforcehttps:
  allowedorigins: []
webapp:
  enabled:
  port:
  analyticstoken:
  scripts: []
rpc:
  enabled:
  port:
logging:
  levels:
    qriapi:
```

or does this make the most sense as some sort of tab completion?
