### ISSUE TITLE
supplying `bodypath` in dataset.yaml doesn't properly read input body

### ISSUE THREAD

**Issue by b5** [qri-io/qri#565]
assuming I have a file `body.json` stored in the same directory as this `dataset.yaml`:
```yaml
name: my_great_dataset
meta:
  title: My Great Dataset
bodypath: body.json
```

I get the following error:
```shell
$ qri new --file dataset.yaml
reading body file: open ./body.json: no such file or directory
```

I can get around it by running:
```shell
qri new --file dataset.yaml --body body.json
created new dataset me/qri_growth_stats@QmQ7hA8gkDACaowX4jAEueRnMihBrvQQqBuZzBs6jEX8QJ/ipfs/QmSLdCz4jUka8so1nWkDUvryENU75rPhoYVw9zJvHn5tTn
```

running without `--body` should instead successfully create a dataset.
